# Generated by Django 6.0.2 on 2026-03-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("andamento", "Em andamento"),
                    ("concluida", "Concluída"),
                ],
                default="aberta",
                max_length=20,
            ),
        ),
    ]
