# Generated by Django 5.1.1 on 2026-04-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="equipamento",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="modelo",
        ),
        migrations.AddField(
            model_name="servico",
            name="tipo_servico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("instalacao", "Instalação"),
                    ("manutencao", "Manutenção"),
                    ("limpeza", "Limpeza"),
                    ("reparo", "Reparo"),
                    ("vistoria", "Vistoria"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("andamento", "Em andamento"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
