# Generated by Django 6.0.2 on 2026-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0002_tarefa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsavel",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="responsavel",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
