# Generated by Django 5.1.1 on 2026-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0002_remove_servico_equipamento_remove_servico_marca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="servicos/documentos/",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="servicos/imagens/",
                verbose_name="Imagem",
            ),
        ),
    ]
