# Generated by Django 5.1.1 on 2026-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0003_servico_documento_servico_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="data_agendada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Agendamento"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="hora_agendada",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora do Agendamento"
            ),
        ),
    ]
