# Generated by Django 6.0.2 on 2026-03-06 02:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0004_cliente_tarefa_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="responsavel",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="cliente",
        ),
        migrations.AddField(
            model_name="cliente",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_servico", models.DateField()),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tarefas.cliente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Projeto",
        ),
        migrations.DeleteModel(
            name="Responsavel",
        ),
        migrations.DeleteModel(
            name="Tarefa",
        ),
    ]
