# Generated by Django 6.0.2 on 2026-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0006_despesa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="telefone",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="valor",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
