# Generated by Django 6.0.2 on 2026-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0007_remove_cliente_criado_em_remove_cliente_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
