# Generated by Django 6.0.2 on 2026-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0008_cliente_email_cliente_endereco_cliente_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="valor_cobrado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
