# Generated by Django 5.1.1 on 2026-03-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0009_servico_valor_cobrado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="documento",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CPF/CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="defeito_relatado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="diagnostico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="equipamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="marca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="modelo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("andamento", "Em andamento"),
                    ("aguardando_peca", "Aguardando peça"),
                    ("concluido", "Concluído"),
                    ("entregue", "Entregue"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicos",
                to="tarefas.cliente",
            ),
        ),
    ]
