# Generated by Django 5.1.1 on 2026-03-20 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0010_cliente_documento_cliente_observacoes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criou", "Criou"),
                            ("alterou", "Alterou"),
                            ("deletou", "Deletou"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("objeto_id", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
