# Generated by Django 5.1.1 on 2026-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0011_logauditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="logauditoria",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="nome_usuario",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("criou", "Criou"),
                    ("alterou", "Alterou"),
                    ("deletou", "Deletou"),
                    ("visualizou", "Visualizou"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="objeto_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
