# Generated by Django 5.1.1 on 2026-03-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0012_logauditoria_ip_logauditoria_nome_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logauditoria",
            old_name="data_hora",
            new_name="data",
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("criou", "Criou"),
                    ("alterou", "Alterou"),
                    ("deletou", "Deletou"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="descricao",
            field=models.TextField(blank=True, default="Sem descrição"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="modelo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="nome_usuario",
            field=models.CharField(blank=True, default="Sem descrição", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="objeto_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
