# Generated by Django 5.1.1 on 2026-03-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0013_rename_data_hora_logauditoria_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("andamento", "Em andamento"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
    ]
