# Generated by Django 5.1.1 on 2026-04-04 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensagens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mensagem",
            options={"ordering": ["data_envio"]},
        ),
        migrations.AlterField(
            model_name="mensagem",
            name="destinatario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens_recebidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mensagem",
            name="remetente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens_enviadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
