# Generated by Django 5.1.1 on 2026-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mensagens",
            "0002_alter_mensagem_options_alter_mensagem_destinatario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="data_leitura",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="entregue",
            field=models.BooleanField(default=False),
        ),
    ]
